version: 2
updates:
  - package-ecosystem: "uv"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 7 * * 1"
      timezone: "America/New_York"
    commit-message:
      prefix: "deps(py)"
      prefix-development: "deps(py-dev)"
    cooldown:
      default-days: 2
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 1
    groups:
      uv-prod-minor-patch:
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      uv-dev-minor-patch:
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 7 * * 1"
      timezone: "America/New_York"
    commit-message:
      prefix: "deps(gha)"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    versioning-strategy: increase
    directory: "web/pingpong/"
    schedule:
      interval: "cron"
      cronjob: "0 7 * * 1"
      timezone: "America/New_York"
    commit-message:
      prefix: "deps(web)"
      prefix-development: "deps(web-dev)"
    ignore:
      - dependency-name: "flowbite-svelte"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "flowbite-svelte-icons"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
    cooldown:
      default-days: 2
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 1
    groups:
      pnpm-prod-minor-patch:
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      pnpm-dev-minor-patch:
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
