"""Add lecture chat manifest storage and transcript cursor

Revision ID: ff54a796106b
Revises: 4c1b8a7d5e6f
Create Date: 2026-04-05 17:46:22.436615

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff54a796106b"
down_revision: Union[str, None] = "4c1b8a7d5e6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lecture_video_thread_states",
        sa.Column(
            "last_chat_context_end_ms", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "lecture_videos", sa.Column("manifest_data", sa.JSON(), nullable=True)
    )
    op.add_column(
        "lecture_videos", sa.Column("manifest_version", sa.Integer(), nullable=True)
    )
    op.add_column(
        "lecture_videos",
        sa.Column(
            "lecture_video_chat_available",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "messages",
        sa.Column(
            "is_hidden", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "is_hidden")
    op.drop_column("lecture_videos", "lecture_video_chat_available")
    op.drop_column("lecture_videos", "manifest_version")
    op.drop_column("lecture_videos", "manifest_data")
    op.drop_column("lecture_video_thread_states", "last_chat_context_end_ms")
    # ### end Alembic commands ###
